name: Fix Readme
on:
  workflow_dispatch:
jobs:
  Fix_Readme:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Edit Readme
        run: |
            curl -o README.md https://raw.githubusercontent.com/${{ github.repository }}/main/README.md
            sed -i "s#FiorenMas/Revanced-And-Revanced-Extended-Non-Root#${{ github.repository }}#g" README.md
      - name: Commit Readme
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'README.md'
          default_author: github_actor
          message: 'Edit Readme'
          push: true
